add omnicored 0.3.1
mpugach/docker_omnicored pull request #1
Opened 2018-09-22 15:37 UTC by nerdDan

Would you consider adding version 0.3.1 as there are some major changes such as segwit support?

2018-09-22 17:31 UTC, mpugach requested changes
thank you @nerdDan, please check the comments

2018-09-22 17:31 UTC, mpugach commented on v0.3.1-alpine/Dockerfile
> +LABEL maintainer="Maksym Pugach <pugach.m@gmail.com>"
please add yourself to the maintainers list

2018-09-22 17:31 UTC, mpugach commented on v0.3.1-alpine/Dockerfile
> +COPY docker-entrypoint.sh /entrypoint.sh
and place the file into the folder

2018-09-23 03:51 UTC, mpugach approved these changes
👍

2018-09-23 03:52 UTC, merged

2018-09-23 03:54 UTC, nerdDan commented
Would you mind publish it to `hub.docker.com`?

2018-09-23 03:56 UTC, mpugach commented
building